### ISSUE TITLE
additional artifacts

### ISSUE THREAD

**Issue by ghost** [Silv3rHorn/ArtifactExtractor#3]
just curious, are you able to extract UsnJrnl:J and files that exists in Recycle Bin?

**Comment by Silv3rHorn** [comment]
Hi,

For UsnJrnl:J, the script is able to do so, as it is based on Joachim Metz's dfVFS libraries which supports NTFS Alternate Data Stream (ADS). However, to do it efficiently, there is a need to extract only the actual data of the sparse stream, which increases the complexity.

For files that exists in Recycle bin, the complexity in doing so depends on whether the original filename of the deleted files should be retained, and whether to map the extracted files to the right user based on SID.

Both are definitely achievable, but not as straightforward as the artifacts that are currently supported.

Regards.

**Comment by ghost** [comment]
I am able to extract the UsnJrnl file except for the J file. I was wondering if there was a way to extract the J file automatically using the artifactextractor. 

My intention was to extract everything (all SIDs) that exists in the Recycle Bin out to be parsed later.

**Comment by Silv3rHorn** [comment]
I am assuming that you have been modifying the code and running the python scripts instead of using the executable based on your reply. Please let me know if I am wrong.

For UsnJrnl, I have pushed out dff1220 in a separate branch to support ADS. Please remember to uncomment line 53 in artifacts.py before attempting the extraction of the Journal file. I commented it out because of what I mentioned in my earlier reply - the inefficiency. On an E01 image that I tested on, a 20GB journal file was extracted when it only contains ~256MB of valid records.

For the extraction of Recycle Bin SID folders, I will attempt to support it on another day.

Regards.

**Comment by ghost** [comment]
Yeah I have been tinkering with the python script instead of the executable as I am thinking of possible ways to make the automation seamless.

I will give it a try tomorrow on a small evidence file and let you know how it goes. Thank you so much for your help.

**Comment by Silv3rHorn** [comment]
If you are using the python script, please take some time to read through the newly updated README.md (0d85639).

**Comment by ghost** [comment]
I did tests on 2 evidence and the usnjrnl files seems to be extracting properly.

**Comment by ghost** [comment]
I tried using the build from dff1220 and realized that ntuser, usrclass and jump lists are not extracting as intended from the previous build.

**Comment by Silv3rHorn** [comment]
I can't seem to reproduce this error. Could you provide more details, and elaborate on what you mean by "not extracting as intended"?

**Comment by ghost** [comment]
I did some tests by commenting and uncommenting the usnjrnl in artifact.py and noticed that when the usnjrnl is uncommented, I will not be able to get any results for ntuser and usrclass. However, if usnjrnl is commented in artifact.py, I am able to get the ntuser and usrclass files. Correct me if I am wrong.

**Comment by Silv3rHorn** [comment]
Thanks for providing the additional information for me to debug. The latest update should fix this issue, and it also adds support for Recycle.bin type artifacts (i.e. recursive extraction of folders).

**Comment by ghost** [comment]
Glad I could help. Alright let me perform some tests on the updated script. Thank you.
