### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ghost** [Silv3rHorn/ArtifactExtractor#5]
Hi,

I run the extractor against a windows 7 ultimate system and encountered the following errors:

UnicodeEncodeError: 'ascii' codec can't encode characters in position 125-128: ordinal not in range(128)

The registry and ntuser files are not extracted after I ran them. Not sure if you encountered the same issue as well. Just curious, if there are more then one partitions on the system (e.g. C, D and E), does the extractor extract the $J from these 3 partitions?

I hope this helps. Thank you.

**Comment by Silv3rHorn** [comment]
Would appreciate if you could provide the full debug information that appear when you encounter the error, and the logfile (sanitize any sensitive information if necessary) created. Thanks.

No, it does not extract the $J from these 3 partitions, only the 1 you have selected.

**Comment by ghost** [comment]
![picture](https://user-images.githubusercontent.com/17736237/33982587-fcd33102-e0eb-11e7-8d3b-4684575870a6.png)
[logfile.txt](https://github.com/Silv3rHorn/ArtifactExtractor/files/1558392/logfile.txt)

I have attached the debug information fyi. Do note that some data in the evidence of the windows 7 is in chinese.

Would be great if we could retrieve $J from multiple ntfs partitions.

**Comment by Silv3rHorn** [comment]
Thanks for providing the files for me to debug. I suspect this error was due to the lack of support by `logging` for unicode characters. I have pushed out a fix in the development branch 5beebf3, but I don't have an image with unicode filenames to test, so please let me know if it fixes your error.

As for retrieving $J from multiple ntfs partitions, looking at your screenshot, you seem to have selected 3 partitions. Hence, the script should have extracted $J from all 3 selected partitions. Let me know if it doesn't.

**Comment by ghost** [comment]
No problem! I got the same error message with the updated new code.

**Comment by Silv3rHorn** [comment]
For a temporary fix, comment out all `logging.info` lines. Will try to create an image with files containing chinese characters filenames to ensure that I fix this

**Comment by ghost** [comment]
Noted thank you. The script does not extract $J from multiple partitions, same for its $MFT.

**Comment by Silv3rHorn** [comment]
I have fixed the unicode logging bug in 245bbb1, added support for multiple partitions in 245bbb1. Also, you can now select all the artifacts you wish to extract using the latest release executable.

**Comment by ghost** [comment]
Thank you so much! let me give it a shot and I will update you if it works.

**Comment by ghost** [comment]
I just tested on the same evidence, the program and logging works. However, it does not loop through and gather the $J or $MFT from other partitions. The only partition with artifacts extracted is from the C drive.

**Comment by Silv3rHorn** [comment]
Did you select all the partitions when prompted?
![all_partitions](https://user-images.githubusercontent.com/2588284/34293687-8e799eb6-e740-11e7-8e60-b7e85214c10a.JPG)

**Comment by ghost** [comment]
Yup! I chose all partitions. Recycle bin files are not there as well.

**Comment by Silv3rHorn** [comment]
For the other partitions besides C:\, are they NTFS? Also, has it been verified that the recycle bin is not empty? If your answers to both questions are yes, would appreciate if you could provide me the commands you used to trigger the script, and send me the log file (with necessary desanitisation). Thanks.

**Comment by ghost** [comment]
Yes they are all NTFS. D drive does not have a $J but a $MFT file. E drive has both $MFT and $J file. All 3 partitions have files in the recycle bin.

The command I used is:
python artifact_extractor.py "Image source" "Destination output"

Attached is the log file for your reference. Thank you for your help.
[logfile.txt](https://github.com/Silv3rHorn/ArtifactExtractor/files/1583809/logfile.txt)

**Comment by Silv3rHorn** [comment]
As you did not specify the artifacts you want, the script defaults to the common artifacts it extracts (without MFT, USNJrnl, Recycle bin files). Please see `python artifact_extractor.py -h` to view how to use the optional argument `-a` to include those artifacts you want (or just use this: `python artifact_extractor.py <image source> <destination> -a std,recycle,mft,usnjrnl`)

**Comment by ghost** [comment]
Ah I see. Yup you using the command you mentioned works!

**Comment by dark6naw** [comment]
Changed my account to this instead. Will update you if there are any issues.
