### ISSUE TITLE
extracted output will be similar to host directory

### ISSUE THREAD

**Issue by dark6naw** [Silv3rHorn/ArtifactExtractor#8]
I was thinking if you would be able to amend the extracted output to be stored as such, it will be good! for example,

HOSTNAME/C
HOSTNAME/C/Windows/System32/config/SOFTWARE
HOSTNAME/C/Windows/System32/config/SYSTEM
HOSTNAME/C/Windows/System32/config/SAM
HOSTNAME/C/Windows/System32/config/SECURITY
HOSTNAME/C/Windows/System32/winevt/Logs/Security.evtx
HOSTNAME/C/Windows/System32/winevt/Logs/Application.evtx
HOSTNAME/C/Windows/inf/setupapi.log
HOSTNAME/C/Windows/inf/setupapi.dev.log

need your input on this. Thank you.

**Comment by Silv3rHorn** [comment]
Support added in 594aa27. VSCs are extracted to the same location as original file to facilitate automated processing with other tools.
